fix(devicescript): switch to standard node image
builds inside the alpine node image failed with a cryptics error message:

```
Error: timeout (3000ms) waiting for response to ZX81/2[1]: 0x80 sz=4: 40050000
    at /app/node_modules/@devicescript/cli/built/devicescript-cli.cjs:54264:11
```